### ISSUE TITLE
Сompiled version

### ISSUE THREAD

**Issue by SPluzh** [rstewa/Audibly#29]
Hi! Could you please compile a version of the program?

**Comment by rstewa** [comment]
I'll take a look tonight. I might have to publish it to the Microsoft store since I don't have a certificate. I'll let you know.

**Comment by rstewa** [comment]
Update: I've submitted my app to the Microsoft Store. I'll update the README once it has hopefully been approved.

**Comment by rstewa** [comment]
@SPluzh I had to make a few bug fixes so I'm having to resubmit it to the store. Hopefully it's approved this time around.

**Comment by rstewa** [comment]
Closing because this app can now be downloaded from the Microsoft store: https://www.microsoft.com/store/productid/9P6R1M1GG9JR?ocid=pdpshare
