### ISSUE TITLE
Import fails

### ISSUE THREAD

**Issue by Henry-Akin** [rstewa/Audibly#43]
App works fine on my laptop, however when I try to run it on my Dell OptiPlex 3060 PC or my HP HP ENVY TE01 it shows that it has imported 59 then seems to freeze trying to import the next file. FYI   Files I am trying to import are Audible Books from audible.com Files are in audio format M4B. File it is currently trying to import is "Cupid Texas: How the Cowboy was Won". All computers are running latest versions of Windows 11 Home. The APP has been running on the HP ENVY computer for over 24 hours and seems to be stuck in a loop with a line repeatedly running left to right in the background.

Henry D. Akin

**Comment by rstewa** [comment]
@Henry-Akin I'll take a look tonight and see if I can figure out what's causing that.

**Comment by Henry-Akin** [comment]
I have tried to give you as much info as I can. If you need more info you can email at the email at akinh@att.net.

**Comment by rstewa** [comment]
@Henry-Akin can you grab the log file for me?

To get the log file:

1. Open Audibly
2. Click on the left side bar
3. Hit `ctrl + shift + f12` at the same time (this opens the hidden debug menu)
![image](https://github.com/rstewa/Audibly/assets/70178227/e960a0f5-6820-46f2-ade0-f9c31d7adbd8)
4. Click on the `Open App State Folder` button.
    - This should open the file explorer
5. Scroll to the bottom and there should hopefully be a file called `Audibly.log`

Can you post that file here?

**Comment by Henry-Akin** [comment]
All systems appear to be having the same issue now. The laptop is a HP laptop hp 15-dw3xx running Windows 11 Home 22H2. This log is from the laptop. Can try to get logs from other devices later if that will help. Right now its bed time. 9am to 2am next is a long for an old man(age 83).

**Comment by Henry-Akin** [comment]
Checked other systems and they are same "can't load image"
[Dell Audibly log.log](https://github.com/user-attachments/files/15740928/Dell.Audibly.log.log)
[HP ENVY Audibly log.log](https://github.com/user-attachments/files/15740929/HP.ENVY.Audibly.log.log)

**Comment by Henry-Akin** [comment]
One other thing I just remembered. Files are being imported from "openaudible" app in all cases

**Comment by Henry-Akin** [comment]
Just checked and it actually imported the file "Cupid Texas: How the Cowboy was won" but that was the last file imported.

**Comment by rstewa** [comment]
> One other thing I just remembered. Files are being imported from "openaudible" app in all cases
This is good to know. I've never heard of openaudible so it may be that they convert the cover image in a weird way. I'll check it out. I've only ever used [Libation](https://github.com/rmcrackan/Libation) to convert my Audible books.

I'm going to take a look at my code for converting the image and get back to you on what I find!

**Comment by rstewa** [comment]
@Henry-Akin Can you do me another favor? I can't ask you to send me the .m4b file because of copyright stuff but I do log the metadata for each book that is imported. Can you send me the metadata file for the book(s) that failed?

To do this:

Repeat the same steps as we did to get the log file:

> 1. Open Audibly
> 2. Click on the left side bar
> 3. Hit `ctrl + shift + f12` at the same time (this opens the hidden debug menu)
>    ![image](https://private-user-images.githubusercontent.com/70178227/337513689-e960a0f5-6820-46f2-ade0-f9c31d7adbd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NzczMTEsIm5iZiI6MTcxNzc3NzAxMSwicGF0aCI6Ii83MDE3ODIyNy8zMzc1MTM2ODktZTk2MGEwZjUtNjgyMC00NmYyLWFkZTAtZjljMzFkN2FkYmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDE2MTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljOTUzMmQyNmE5NTQ0MDE3NmRmNTAxMTRhODUwNWNkODc4MWI5MzBmMWI2NzljZTk5NjRjNjZiM2VjMjljNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ERKxmhWE9mLd6jH4jQZGxW_WdZAT0avpo1wOU9PHxX4)
> 4. Click on the `Open App State Folder` button.
>    
>    * This should open the file explorer

In the file explorer you should see a folder for every book that was imported. There is a metadata file inside each folder called `Metadata.json`.

![image](https://github.com/rstewa/Audibly/assets/70178227/6eea3e81-0f4a-4c69-ba53-34dbddde1ade)

Can you send me this file for the book(s) that were failing? This will allow me to see what image data Audibly was able to get and see what kind of format it's in.

**Comment by rstewa** [comment]
@Henry-Akin Also, I did look into OpenAudible but I wasn't able to use it because it costs money and I don't want to pay for something I'll probably never use again

**Comment by Henry-Akin** [comment]
This is the file off my HP ENVY for "Cupid Texas:How the Cowboy was won".  I know it can be a real pain to chase this kind of issue. I am a retired Tech Pubs Consultant.
________________________________

**Comment by Henry-Akin** [comment]
"Openaudible" is a new app from Audible.com (Amazon)
________________________________

**Comment by Henry-Akin** [comment]
For some reason it seems to handle the Art well, it's the audio it seems to have problems.  Don't mind working with yo to solve this problem. Just let what you need.
I am a retired Electronic tech with a little 60 years background in Maintenace, Tech Pubs, Installation, etc....
________________________________

**Comment by rstewa** [comment]
@Henry-Akin It's no problem. I'm just happy that there are other people using my app. And that's awesome. Hopefully we can get this issue worked out.

Also, if you could send me that `Metadata.json` file that'll help me get started. I still think it's probably an image problem.

**Comment by rstewa** [comment]
@Henry-Akin if it is easier, you can email me at rstewa@proton.me

**Comment by rstewa** [comment]
@Henry-Akin Are you sure you sent it? I'm not seeing any attachments. Could you maybe go on GitHub and attach it to a comment?

**Comment by Henry-Akin** [comment]
[Metadata.json](https://github.com/user-attachments/files/15745284/Metadata.json)

Here is the metadata file from my Dell OptiPlex 3060

**Comment by rstewa** [comment]
@Henry-Akin awesome I got it. Taking a look now

**Comment by Henry-Akin** [comment]
Thanks for cluing me on libations. It works well, NO hangups. NO CHOKES. I think issues may be between Audibly and how OpenAudible converts aax files to m4b files.

Again Audibly has NO ISSUES when using Libation as audiobook source.

Henry

________________________________

**Comment by Henry-Akin** [comment]
Hope this helps some. My issues of playing my books on my computer have been solved by changing to the "libations app" to download .aax format files from Audible and convert to .m4b files. The Ability app works correctly on my 3 systems now using the libations app as an import source. Once again thank you for giving me a headsup on the libations app. Of course, there still remains the issue of it not working correctly with the "Openaudible" app.      
Henry Akin

**Comment by rstewa** [comment]
@Henry-Akin Yeah, I'll try to see if I can figure out what's causing that but I'm not going to rush to fix it since you were able to get things working with Libation. Glad you like it. It's a great tool that I've been using for a while! I'm going to close this issue for now and let me know if you have any other issues or recommendations for Audibly!

**Comment by Henry-Akin** [comment]
One other thing of note is that your product is a suggested app for listing. That is why I came to you. Since this is a recent event you may have more similar issues come up relating to your product and "openaudible" not working together.

________________________________

**Comment by openaudible** [comment]
In my case this happened because the file name got too long and the meta directory couldn't be created. I sent @rstewa a quick suggestion on a fix.

**Comment by rstewa** [comment]
this fix will be in v2.0.10.0
