### ISSUE TITLE
Chapter gadget moves

### ISSUE THREAD

**Issue by Henry-Akin** [rstewa/Audibly#45]
The chapter gadget moves on the control bar depending on length on document title. At times it goes behind other gadgets and becomes unfunctional at times. Depends on where it is.

**Comment by Henry-Akin** [comment]
![Screenshot 2024-06-09 112105](https://github.com/rstewa/Audibly/assets/64620115/1408fb3f-53fa-4deb-8a05-efd530aa6150)
![Screenshot 2024-06-09 112148](https://github.com/rstewa/Audibly/assets/64620115/9002cb45-f75f-4cd7-b7ae-268e0e5f0d0e)
![Screenshot 2024-06-09 112219](https://github.com/rstewa/Audibly/assets/64620115/7d738d70-dc78-4829-94a3-1d6db570854f)
Maybe these snaps will help

**Comment by Henry-Akin** [comment]
Maybe set it to a fixed location under the title.

**Comment by Henry-Akin** [comment]
After looking at things I guess I should have called it the what is playing gadget.

**Comment by Henry-Akin** [comment]
To clear things a little. It doesn't not work if accessed on any part of it that is behind another gadget like the one effecting start stop back forward. It will work if accessed from any part of it not behind another gadget.

**Comment by rstewa** [comment]
@Henry-Akin I'll take a look. Thanks for finding this!

**Comment by Henry-Akin** [comment]
If you need someone to take a independent look at something just ask. Just don't ask me to look code.

________________________________________

**Comment by rstewa** [comment]
fixed in bead0a3. It'll be in my next release to the store which should hopefully happen this week @Henry-Akin
